[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.12"

[features]
seeds = false
skip-lint = false

[programs.localnet]
# Will be replaced by `anchor keys sync`
bounty_board = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"